package org.hacker.mvc.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("w_db_model", "id", DbModel.class);
		arp.addMapping("w_db_model_item", "id", DbModelItem.class);
		arp.addMapping("w_db_model_mapping", "id", DbModelMapping.class);
		arp.addMapping("w_folder", "id", Folder.class);
		arp.addMapping("w_generate", "id", Generate.class);
		arp.addMapping("w_interface", "id", Interface.class);
		arp.addMapping("w_interface_log", "id", InterfaceLog.class);
		arp.addMapping("w_parameter", "id", Parameter.class);
		arp.addMapping("w_project", "id", Project.class);
		arp.addMapping("w_result_data", "id", ResultData.class);
	}
}

