package org.hacker.mvc.model;

import org.hacker.core.plugin.Table;

import org.hacker.mvc.model.base.BaseFolder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Table(tableName="w_folder")
public class Folder extends BaseFolder<Folder> {
	public static final Folder dao = new Folder();
}
