package org.hacker.mvc.model;

import org.hacker.core.plugin.Table;

import org.hacker.mvc.model.base.BaseInterface;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Table(tableName="w_interface")
public class Interface extends BaseInterface<Interface> {
	public static final Interface dao = new Interface();
}
