package org.hacker.mvc.model;

import org.hacker.core.plugin.Table;

import org.hacker.mvc.model.base.BaseInterfaceLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Table(tableName="w_interface_log")
public class InterfaceLog extends BaseInterfaceLog<InterfaceLog> {
	public static final InterfaceLog dao = new InterfaceLog();
}
