package org.hacker.mvc.model;

import org.hacker.core.plugin.Table;

import org.hacker.mvc.model.base.BaseSimulationData;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Table(tableName="w_simulation_data")
public class SimulationData extends BaseSimulationData<SimulationData> {
	public static final SimulationData dao = new SimulationData();
}
