package org.hacker.mvc.model.base;

import org.hacker.core.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseInterface<M extends BaseInterface<M>> extends BaseModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setCode(java.lang.String code) {
		set("code", code);
	}

	public java.lang.String getCode() {
		return get("code");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setRelativeUrl(java.lang.String relativeUrl) {
		set("relative_url", relativeUrl);
	}

	public java.lang.String getRelativeUrl() {
		return get("relative_url");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}

	public java.lang.String getDescription() {
		return get("description");
	}

	public void setWProjectId(java.lang.Integer wProjectId) {
		set("w_project_id", wProjectId);
	}

	public java.lang.Integer getWProjectId() {
		return get("w_project_id");
	}

	public void setWFolderId(java.lang.Integer wFolderId) {
		set("w_folder_id", wFolderId);
	}

	public java.lang.Integer getWFolderId() {
		return get("w_folder_id");
	}

}
