package org.hacker.mvc.model.base;

import org.hacker.core.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseParameter<M extends BaseParameter<M>> extends BaseModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setType(java.lang.String type) {
		set("type", type);
	}

	public java.lang.String getType() {
		return get("type");
	}

	public void setRequire(java.lang.Boolean require) {
		set("require", require);
	}

	public java.lang.Boolean getRequire() {
		return get("require");
	}

	public void setFormat(java.lang.String format) {
		set("format", format);
	}

	public java.lang.String getFormat() {
		return get("format");
	}

	public void setLength(java.lang.String length) {
		set("length", length);
	}

	public java.lang.String getLength() {
		return get("length");
	}

	public void setRemarks(java.lang.String remarks) {
		set("remarks", remarks);
	}

	public java.lang.String getRemarks() {
		return get("remarks");
	}

	public void setWInterfaceId(java.lang.Integer wInterfaceId) {
		set("w_interface_id", wInterfaceId);
	}

	public java.lang.Integer getWInterfaceId() {
		return get("w_interface_id");
	}

}
