package org.hacker.mvc.model.base;

import org.hacker.core.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSimulationData<M extends BaseSimulationData<M>> extends BaseModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setData(java.lang.String data) {
		set("data", data);
	}

	public java.lang.String getData() {
		return get("data");
	}

	public void setWInterfaceId(java.lang.Integer wInterfaceId) {
		set("w_interface_id", wInterfaceId);
	}

	public java.lang.Integer getWInterfaceId() {
		return get("w_interface_id");
	}

}
