package org.hacker.mvc.model.base;

import org.hacker.core.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseResultData<M extends BaseResultData<M>> extends BaseModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setValue(byte[] value) {
		set("value", value);
	}

	public byte[] getValue() {
		return get("value");
	}

	public void setWInterfaceId(java.lang.Integer wInterfaceId) {
		set("w_interface_id", wInterfaceId);
	}

	public java.lang.Integer getWInterfaceId() {
		return get("w_interface_id");
	}

	public void setWMetaDataId(java.lang.Integer wMetaDataId) {
		set("w_meta_data_id", wMetaDataId);
	}

	public java.lang.Integer getWMetaDataId() {
		return get("w_meta_data_id");
	}

}
