package org.hacker.mvc.model;

import org.hacker.core.plugin.Table;

import org.hacker.mvc.model.base.BaseDbModelItem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Table(tableName="w_db_model_item")
public class DbModelItem extends BaseDbModelItem<DbModelItem> {
	public static final DbModelItem dao = new DbModelItem();
}
