package org.hacker.mvc.model;

import org.hacker.core.plugin.Table;

import org.hacker.mvc.model.base.BaseDbModel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Table(tableName="w_db_model")
public class DbModel extends BaseDbModel<DbModel> {
	public static final DbModel dao = new DbModel();
}
