package org.hacker.mvc.model;

import org.hacker.core.plugin.Table;

import org.hacker.mvc.model.base.BaseDbModelMapping;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Table(tableName="w_db_model_mapping")
public class DbModelMapping extends BaseDbModelMapping<DbModelMapping> {
	public static final DbModelMapping dao = new DbModelMapping();
}
