package org.hacker.mvc.model;

import org.hacker.core.plugin.Table;

import org.hacker.mvc.model.base.BaseGenerate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Table(tableName="w_generate")
public class Generate extends BaseGenerate<Generate> {
	public static final Generate dao = new Generate();
}
