package org.hacker.mvc.model;

import org.hacker.core.plugin.Table;

import org.hacker.mvc.model.base.BaseMetaData;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Table(tableName="w_meta_data")
public class MetaData extends BaseMetaData<MetaData> {
	public static final MetaData dao = new MetaData();
}
