package org.hacker.mvc.model;

import org.hacker.core.plugin.Table;

import org.hacker.mvc.model.base.BaseParameter;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Table(tableName="w_parameter")
public class Parameter extends BaseParameter<Parameter> {
	public static final Parameter dao = new Parameter();
}
