package org.hacker.mvc.model;

import org.hacker.core.plugin.Table;

import org.hacker.mvc.model.base.BaseResultData;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Table(tableName="w_result_data")
public class ResultData extends BaseResultData<ResultData> {
	public static final ResultData dao = new ResultData();
}
