package org.hacker.core.config;

import com.jfinal.plugin.activerecord.generator.BaseModelGenerator;

public class CustomBaseModelGenerator extends BaseModelGenerator{
	
	public CustomBaseModelGenerator(String baseModelPackageName, String baseModelOutputDir) {
		super(baseModelPackageName, baseModelOutputDir);
		this.importTemplate = 
				"import org.hacker.core.BaseModel;%n" +
				"import com.jfinal.plugin.activerecord.IBean;%n%n";
		this.classDefineTemplate =
			"/**%n" +
			" * Generated by JFinal, do not modify this file.%n" +
			" */%n" +
			"@SuppressWarnings(\"serial\")%n" +
			"public abstract class %s<M extends %s<M>> extends BaseModel<M> implements IBean {%n%n";
	}

}
