package org.hacker.mvc.model.base;

import org.hacker.core.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDbModelItem<M extends BaseDbModelItem<M>> extends BaseModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setNote(java.lang.String note) {
		set("note", note);
	}

	public java.lang.String getNote() {
		return get("note");
	}

	public void setType(java.lang.String type) {
		set("type", type);
	}

	public java.lang.String getType() {
		return get("type");
	}

	public void setJavaType(java.lang.String javaType) {
		set("java_type", javaType);
	}

	public java.lang.String getJavaType() {
		return get("java_type");
	}

	public void setLength(java.lang.Integer length) {
		set("length", length);
	}

	public java.lang.Integer getLength() {
		return get("length");
	}

	public void setDecimal(java.lang.Integer decimal) {
		set("decimal", decimal);
	}

	public java.lang.Integer getDecimal() {
		return get("decimal");
	}

	public void setSerial(java.lang.Integer serial) {
		set("serial", serial);
	}

	public java.lang.Integer getSerial() {
		return get("serial");
	}

	public void setFormat(java.lang.String format) {
		set("format", format);
	}

	public java.lang.String getFormat() {
		return get("format");
	}

	public void setIsPrimary(java.lang.Boolean isPrimary) {
		set("is_primary", isPrimary);
	}

	public java.lang.Boolean getIsPrimary() {
		return get("is_primary");
	}

	public void setIsRequired(java.lang.Boolean isRequired) {
		set("is_required", isRequired);
	}

	public java.lang.Boolean getIsRequired() {
		return get("is_required");
	}

	public void setDefaultValue(java.lang.String defaultValue) {
		set("default_value", defaultValue);
	}

	public java.lang.String getDefaultValue() {
		return get("default_value");
	}

	public void setWModelId(java.lang.Integer wModelId) {
		set("w_model_id", wModelId);
	}

	public java.lang.Integer getWModelId() {
		return get("w_model_id");
	}

}
