package org.hacker.mvc.model.base;

import org.hacker.core.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseInterfaceLog<M extends BaseInterfaceLog<M>> extends BaseModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setAccess(java.lang.Integer access) {
		set("access", access);
	}

	public java.lang.Integer getAccess() {
		return get("access");
	}

	public void setStartDate(java.util.Date startDate) {
		set("start_date", startDate);
	}

	public java.util.Date getStartDate() {
		return get("start_date");
	}

	public void setEndDate(java.util.Date endDate) {
		set("end_date", endDate);
	}

	public java.util.Date getEndDate() {
		return get("end_date");
	}

	public void setMilliseconds(java.math.BigDecimal milliseconds) {
		set("milliseconds", milliseconds);
	}

	public java.math.BigDecimal getMilliseconds() {
		return get("milliseconds");
	}

	public void setWInterfaceId(java.lang.Integer wInterfaceId) {
		set("w_interface_id", wInterfaceId);
	}

	public java.lang.Integer getWInterfaceId() {
		return get("w_interface_id");
	}

}
